apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/sandeepkavya/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 29 May 2025 20:57:36 IST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: cluster_info
    server: https://127.0.0.1:50102
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 29 May 2025 20:57:36 IST
        provider: minikube.sigs.k8s.io
        version: v1.36.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/sandeepkavya/.minikube/profiles/minikube/client.crt
    client-key: /Users/sandeepkavya/.minikube/profiles/minikube/client.key
